### ISSUE TITLE
test vector #4

### ISSUE THREAD

**Issue by ericlagergren** [jedisct1/zig-rocca-s#1]
Hi Frank. I'm curious if you tried all four test vectors in the paper. It appears like the tag in vector #4 is incorrect?

**Comment by jedisct1** [comment]
Hi Eric!

I just checked, and indeed got different results for test vector #4:

```text
c: 348b6f6efad807d246ebf345e730d83eeb7909d76c6b31a15abd8d9d9c912b54c1b61eb6c5c0cbb8faedfbabb4b57f437260d6f2cca46efcadfc4765fffe9f09
tag: f3b43bc8a160b637e77e231dad96815e
```

The message and AD lengths are the same as text vector #3 that passes just fine, so this is a bit surprising.

Are you getting the same thing with your implementation?

**Comment by jedisct1** [comment]
Ah, scratch that, I'm actually getting the expected tag.

I my case, I originally didn't properly set the `AD` length, which is 18 bytes.

**Comment by ericlagergren** [comment]
Oh! I didn’t notice that either: https://github.com/ericlagergren/rocca/commit/69d44394721c4324dd55778e70f52e7862fc903c

Thanks, good catch!
