### ISSUE TITLE
Internet Draft 03

### ISSUE THREAD

**Issue by samuel-lucas6** [jedisct1/zig-rocca-s#2]
There's a [new version](https://datatracker.ietf.org/doc/html/draft-nakano-rocca-s-03) of the Internet Draft that seems to have [changed the finalization](https://author-tools.ietf.org/iddiff?url2=draft-nakano-rocca-s-03). They also claim 128-bit key-committing security in the draft now.

**Comment by jedisct1** [comment]
Thank you!
